import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ChakraProviders } from "@/providers/chakraprovider";
import React from "react";
import {cn} from "@/lib/utils";

const inter = Inter({
    subsets: ["latin"],
    variable: "--font-inter"
});

export const metadata: Metadata = {
  title: "Afrix Lab",
  description: "Generated by create next app",
}

type RootLayoutProps = {
    children: React.ReactNode;
}

export default function RootLayout({
  children}:RootLayoutProps) {
  return (
    <html lang="en">
      <body  className={cn(
          "antialiased font-inter",
          inter.variable
      )}>
        <ChakraProviders>{children}</ChakraProviders>
      </body>
    </html>
  );
}
